name: RealAdminTools
main: fr.crafter.tickleman.realadmintools.RealAdminToolsPlugin
version: 0.34
website: http://plugins.crafter.fr/tickleman/RealAdminTools/
author: tickleman
depend: [RealPlugin]
commands:
  bench:
    description: benchmark and plugin events debugging process
    usage: /<command>
  commands:
    description: display a list of commands that collapse
    usage: /<command> [<all>]
  config:
    description: change configuration options from server.properties
    usage: /<command> [<option> [<value>]]
  entities:
    description: entities summary
    usage: /<command> [detail]
  ops:
    description: display operators list
    usage: /<command>
  qt:
    description: quick teleporter
    usage: /qt x z | /qt x y z
  tasks:
    description: display tasks list
    usage: /<command>
